### PR TITLE
Fix importing from modules

### PR DESCRIPTION
**Pull request by KTibow**

### CODE REVIEW

**Comment by extremeheat** [comment]
What does this fix? Can you provide example code on replit/runkit that fails before and passes now?

It seems to me like you are not changing anything minus deleting the .mjs wrapper. There is no difference in JS doing 
```js
module.exports = v
v.Vec3 = Vec3
```

and
```js
module.exports = v
module.exports.Vec3 = Vec3
```

as they are both objects pointing to the same thing.

**Comment by KTibow** [comment]
In fact there is. I can't find the blog post that said this, but I tested this on my own machine and this lets `import { Vec3 } from "vec3"` work.

**Comment by extremeheat** [comment]
Please provide an example on repit/runkit or similar tool that demonstrate what changes. This doesn't seem right to me.

**Comment by KTibow** [comment]
[Screencast from 2023-02-23 09-21-14.webm](https://user-images.githubusercontent.com/10727862/220982464-5c20c641-cb33-42a8-8af1-2d9a0a6dbff7.webm)

**Comment by KTibow** [comment]
https://2ality.com/2022/10/commonjs-named-exports.html

**Comment by extremeheat** [comment]
I looked into the source code and see that this interop was a recent change to Node.js, merged in 2020. 

Seems like a giant hack to me, but worthwhile for the sake of compatibility. Naturally there is a large percent of modules that wouldn't work with this compatibility feature. https://github.com/nodejs/node/pull/35249

As written there by @guybedford :

> Specifically on that point, users writing CommonJS shouldn't be "designing" their CommonJS to support this detection. In those cases they should rather just ship an ES module wrapper. What we are more concerned about is how users import CommonJS from ESM and their understanding of this process, and there specifically for CommonJS projects that aren't necessarily well-maintained or being updated with new ESM support.

So seems to me there is no reason to merge this to make it work with that compat hack given the current master that already has a proper module wrapper.

**Pull request closed without merging**
